[adminlogs]
server_name = "alamo"

[game]
desc = "海兵隊員として謎の救難信号に対応したり、ゼノノイドとして自分の巣を作り上げ、海兵隊員から巣を守ったりしよう。"
hostname = "[JP][MRP]田島海兵隊14"

[hub]
tags = "lang:ja,region:as_se,rp:med"

[loki]
name = "alamo"
